site_name: code-docs-generator
theme:
  icon:
    admonition:
      example: simple/libreofficemath
  name: material
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - navigation.path
  - content.footnote.tooltips
  - content.code.copy
  - content.code.select
  - content.code.annotate
  language: en
  palette:
  - scheme: default
    primary: indigo
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - scheme: slate
    primary: lime
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
markdown_extensions:
- def_list
- footnotes
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- admonition
- pymdownx.details
- pymdownx.superfences
- attr_list
- pymdownx.emoji
- pymdownx.tasklist:
    custom_checkbox: true
- md_in_html
- pymdownx.arithmatex:
    generic: true
extra:
  annotate:
    json:
    - .s2
plugins:
- search
- mkdocstrings
- glightbox
- mkdocs-jupyter
extra_css:
- stylesheets/extra.css
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
extra_javascript:
- javascripts/katex.js
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
- https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
nav:
- Home: README.md
- Quickstart:
  - Overview: quickstart/index.md
- Setups:
  - Overview: setups/index.md
- Assumptions:
  - Overview: assumptions/index.md
- Alternatives:
  - Overview: alternatives/index.md
- Functionality:
  - Ai: functionality/ai.md
  - Ai Logic: functionality/ai_logic.md
  - Cli: functionality/cli.md
  - Core: functionality/core.md
  - Overview: functionality/index.md
  - Utils: functionality/utils.md
  - Wizard: functionality/wizard.md
- Architecture:
  - Overview: architecture/index.md
- API:
  - Cli: api/cli.md
  - Ai Logic: api/ai_logic.md
  - Core: api/core.md
  - Ai: api/ai.md
  - Wizard: api/wizard.md
  - Utils: api/utils.md
